### ISSUE TITLE
Auto-Start

### ISSUE THREAD

**Issue by BenMcLean** [sourcebox/sysex-drop#3]
I like how this app is nice and fast. But it could be even faster.
I suggest adding a check box for "Auto-Start"
If checked, then the "Start" button would be disabled and the app would immediately transfer any .syx file dropped. No button pushing required.

The goal here being the ability to try lots of patches real fast. Fewer clicks is better.

**Comment by sourcebox** [comment]
You're right, I already considered to add this feature myself. So expect it in the next release ;-)
I thought a little bit about it and came to the conclusion that I will leave the "Start" button enabled. This should not do any harm because the transfer will start as soon as you drop the file, but in case something goes wrong (e.g. the device has some trouble), you can easily use it to repeat the transfer. Otherwise you would have to drop the file again.

**Comment by BenMcLean** [comment]
This new feature (included in the new build under the Actions tab) worked great and I was able to try out lots of patches from the [The Reface DX Legacy Project](http://refacedx.martintarenskeen.nl/) real fast.
